# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('headline', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('reporter', models.ManyToManyField(to='bookform.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=100)),
                ('rep_category', models.CharField(max_length=100)),
            ],
        ),
    ]
